// import Image from 'next/image';
import Head from 'next/head';
import type { NextPage } from 'next';

import Tile from '@components/player/tiles/tile';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Tile value={1} color="black" />
        <Tile value={2} color="red" />
        <Tile value={3} color="green" />
        <Tile value={4} color="blue" />
        <Tile value={5} color="purple" />
        <Tile value={6} color="yellow" />
        <Tile value={7} color="black" />
      </main>
    </>
  );
};

export default Home;
